Update event schema and data type updates
ONSdigital/zebedee pull request #598
Opened 2022-03-03 14:34 UTC by bpathak-ons

### What

* Schema updates for an event with two new fields
* Data Types updates

### How to review

* code sense check
* CI pass

### Who can review

* Anyone

2022-03-03 14:45 UTC, bpathak-ons commented on zebedee-cms/src/main/java/com/github/onsdigital/zebedee/kafka/KafkaClient.java
> +     * @param traceID the ID of the collection being published
text update

2022-03-03 15:05 UTC, nshumoogum requested changes

2022-03-03 15:05 UTC, nshumoogum commented on zebedee-cms/src/main/java/com/github/onsdigital/zebedee/model/publishing/Publisher.java
> +            kafkaServiceSupplier.getService().produceContentPublished(collection.getId(), uris, dataType, "", "ONS", traceId);
Should we be creating `public static final String SEARCHINDEX = "ONS";`

And then doing the following:

```suggestion
            kafkaServiceSupplier.getService().produceContentPublished(collection.getId(), uris, dataType, "", SEARCHINDEX, traceId);
```

2022-03-03 15:05 UTC, nshumoogum commented on zebedee-cms/src/main/java/com/github/onsdigital/zebedee/model/publishing/Publisher.java
> +        sendMessage (collection, reviewedUris, "legacy");
Same here, `public static final String LEGACYCONTENTFLAG = "legacy";`

```suggestion
        sendMessage (collection, reviewedUris, LEGACYCONTENTFLAG);
```

Maybe there is a better variable name then `LEGACYCONTENTFLAG`

2022-03-04 11:12 UTC, nshumoogum approved these changes

2022-03-09 12:20 UTC, nshumoogum approved these changes

2022-03-09 12:20 UTC, merged