Feature/decommission cache
ONSdigital/zebedee pull request #736
Opened 2024-06-19 09:31 UTC by AWitcherONS

### What

The removal of Enable Legacy Cache  now that legacy cache is permanently active

### How to review

1. Build
2. Audit
3. Lint 
4. Test
5. Manual testing 
      Zebedee Read no action but should work as expected
      Zebedee CMS :-
                Publication Notification has been tested
                       Manual Publication of simple collection
                       Scheduled Publication of simple collection

### Who can review

any one but me

2024-06-19 09:55 UTC, lindenmckenzie requested changes
Some comments on comments :D - also don't forget the readme.

2024-06-19 09:55 UTC, lindenmckenzie commented on zebedee-cms/src/main/java/com/github/onsdigital/zebedee/model/publishing/PublishNotification.java
> +//        }
Should be removing this, not just commenting it out.

2024-06-19 09:55 UTC, lindenmckenzie commented on zebedee-cms/src/main/java/com/github/onsdigital/zebedee/model/publishing/PublishNotification.java
> +//        if (Configuration.isLegacyCacheAPIEnabled()) {
Should be removing this, not just commenting it out.

2024-06-19 11:55 UTC, lindenmckenzie requested changes
Reformat required - still missing the readme as well

2024-06-19 11:55 UTC, lindenmckenzie commented on zebedee-cms/src/main/java/com/github/onsdigital/zebedee/model/publishing/PublishNotification.java
>      public void sendNotification(EventType eventType) {
This needs a reformat now the if condition has been removed.

2024-07-02 10:24 UTC, lindenmckenzie requested changes
Few comments - happy to take these forward in the team now or for you to take them forward, up to you. Additionally - the readme hasn't been updated.

2024-07-02 10:24 UTC, lindenmckenzie commented on zebedee-cms/src/main/java/com/github/onsdigital/zebedee/model/publishing/PublishNotification.java
> -        // Delay the clearing of the cache after publish to minimise load on the server while publishing.
I think this comment is still relevant.

2024-07-02 10:24 UTC, lindenmckenzie commented on zebedee-cms/src/main/java/com/github/onsdigital/zebedee/model/publishing/PublishNotification.java
> +                //  'approved' for storing list of (upcoming) pages
I think these comments are still relevant.

2024-07-02 10:24 UTC, lindenmckenzie commented on zebedee-cms/src/main/java/com/github/onsdigital/zebedee/model/publishing/PublishNotification.java
> -            if (eventType.equals(EventType.APPROVED) || eventType.equals(EventType.PUBLISHED)) {
We still need to send the message on PUBLISHED.

2024-07-09 09:46 UTC, Oluwawunmi submitted a review, later dismissed

2024-07-09 09:54 UTC, Oluwawunmi approved these changes

2024-07-09 10:01 UTC, lindenmckenzie approved these changes

2024-07-09 10:01 UTC, merged